version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pc
      POSTGRES_PASSWORD: password
      PG_DATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
  app:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pc
      - SPRING_DATASOURCE_USERNAME=pc
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: